version: '3'
services:
  educa:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/educa2
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lerton
      - POSTGRES_PASSWORD=lerton123

volumes:
  postgres_data:
    name: educa_db
  