# Generated by Django 5.2.3 on 2025-07-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile_image',
            field=models.FileField(default='media/trainer-2.jpg', upload_to='accounts/profile/img/'),
        ),
    ]
