# Generated by Django 5.2.3 on 2025-07-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_image',
            field=models.FileField(default='trainer-2.jpg', upload_to='accounts/profile/img/'),
        ),
    ]
