# Generated by Django 5.2.3 on 2025-07-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.FileField(upload_to='course/covers'),
        ),
    ]
